# Generated by Django 2.1.4 on 2018-12-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_title', models.CharField(max_length=250)),
                ('article_body', models.TextField()),
            ],
        ),
    ]
