# Generated by Django 2.1.4 on 2018-12-29 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_title',
            new_name='article_heading',
        ),
    ]
